DROP TABLE IF EXISTS npc_training_run_artifact;
DROP TABLE IF EXISTS npc_training_run_log_chunk;
DROP TABLE IF EXISTS npc_training_run_event;
DROP TABLE IF EXISTS npc_training_run;
DROP TABLE IF EXISTS npc_dataset_snapshot_item;
DROP TABLE IF EXISTS npc_dataset_snapshot;
DROP TABLE IF EXISTS npc_review_decision_event;
DROP TABLE IF EXISTS npc_review_task;
DROP TABLE IF EXISTS npc_preference_pair;
DROP TABLE IF EXISTS npc_sft_candidate;
DROP TABLE IF EXISTS npc_episode_turn;
DROP TABLE IF EXISTS npc_episode;
DROP TABLE IF EXISTS npc_review_decision_audit;
DROP TABLE IF EXISTS npc_world_instances;

DROP TABLE IF EXISTS review_decision_audit;
DROP TABLE IF EXISTS world_instances;

CREATE TABLE npc_world_instances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id VARCHAR(128) NOT NULL,
    scenario_id VARCHAR(128) NOT NULL,
    storage_path VARCHAR(512),
    state_version INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE npc_review_decision_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_kind VARCHAR(16),
    review_id VARCHAR(255),
    decision VARCHAR(32),
    reviewer VARCHAR(255),
    notes TEXT,
    decided_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE npc_episode (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_uid VARCHAR(64) NOT NULL,
    scenario_id VARCHAR(128) NOT NULL,
    world_instance_id VARCHAR(128),
    started_at TIMESTAMP,
    ended_at TIMESTAMP,
    exported_at TIMESTAMP,
    resolved BOOLEAN,
    resolution_type VARCHAR(32),
    sacrificed_npc_id VARCHAR(64),
    sacrificed_label VARCHAR(255),
    final_round INTEGER,
    final_state_json JSON,
    export_paths_json JSON,
    source_file_path VARCHAR(512),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE npc_episode_turn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_id BIGINT,
    turn_index INTEGER,
    round_before INTEGER,
    round_after INTEGER,
    npc_id VARCHAR(64),
    target_npc_id VARCHAR(64),
    input_mode VARCHAR(32),
    action_name VARCHAR(64),
    raw_player_text TEXT,
    normalized_input_summary TEXT,
    prompt_context_summary TEXT,
    prompt_bundle_json JSON,
    assistant_output_json JSON,
    state_impact_json JSON,
    provider_mode VARCHAR(32),
    interaction_model VARCHAR(128),
    fallback_model VARCHAR(128),
    reply_adapter_mode VARCHAR(32),
    reply_adapter_applied BOOLEAN,
    deterministic_fallback_used BOOLEAN,
    generation_meta_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE npc_sft_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_key VARCHAR(255),
    canonical_row_key VARCHAR(255),
    episode_id BIGINT,
    episode_turn_id BIGINT,
    source_kind VARCHAR(32),
    instruction_text TEXT,
    prompt_bundle_json JSON,
    assistant_output_json JSON,
    metadata_json JSON,
    rubric_hints_json JSON,
    filter_result_json JSON,
    judge_result_json JSON,
    weighted_judge_score NUMERIC(8, 2),
    judge_confidence NUMERIC(6, 2),
    strategy_label VARCHAR(64),
    scenario_id VARCHAR(128),
    npc_id VARCHAR(64),
    target_npc_id VARCHAR(64),
    input_mode VARCHAR(32),
    deterministic_fallback_used BOOLEAN,
    source_export_path VARCHAR(512),
    source_label VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE npc_preference_pair (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pair_key VARCHAR(512),
    pair_fingerprint VARCHAR(64),
    grouping_strategy VARCHAR(32),
    grouping_key TEXT,
    prompt_bundle_json JSON,
    chosen_candidate_id BIGINT,
    rejected_candidate_id BIGINT,
    pair_reason_json JSON,
    weighted_gap NUMERIC(8, 2),
    pair_confidence NUMERIC(6, 2),
    preference_strength NUMERIC(6, 2),
    judge_result_json JSON,
    pair_decision VARCHAR(32),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE npc_review_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_uid VARCHAR(255),
    review_kind VARCHAR(16),
    sft_candidate_id BIGINT,
    preference_pair_id BIGINT,
    bucket VARCHAR(32),
    priority VARCHAR(16),
    status VARCHAR(16),
    review_required BOOLEAN,
    queue_reason VARCHAR(255),
    selection_reasons_json JSON,
    selection_metrics_json JSON,
    llm_first_pass_json JSON,
    checklist_json JSON,
    current_decision VARCHAR(32),
    current_reviewer VARCHAR(255),
    current_reviewed_at TIMESTAMP,
    current_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE npc_review_decision_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_task_id BIGINT,
    decision VARCHAR(32),
    status_after VARCHAR(16),
    reviewer VARCHAR(255),
    notes TEXT,
    checklist_json JSON,
    decided_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE npc_dataset_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_uid VARCHAR(64),
    dataset_kind VARCHAR(16),
    dataset_version VARCHAR(128),
    snapshot_fingerprint VARCHAR(64),
    source_fingerprint VARCHAR(64),
    manifest_json JSON,
    summary_json JSON,
    output_uri VARCHAR(512),
    is_active BOOLEAN,
    generated_by VARCHAR(255),
    generated_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE npc_dataset_snapshot_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT,
    item_kind VARCHAR(24),
    split_name VARCHAR(16),
    position_index INTEGER,
    sft_candidate_id BIGINT,
    preference_pair_id BIGINT,
    inclusion_reason VARCHAR(64),
    row_fingerprint VARCHAR(64),
    row_payload_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE npc_training_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_uid VARCHAR(64),
    run_kind VARCHAR(16),
    state VARCHAR(16),
    current_step VARCHAR(32),
    message TEXT,
    source_snapshot_id BIGINT,
    parent_run_id BIGINT,
    base_model VARCHAR(255),
    output_adapter_path VARCHAR(512),
    output_adapter_version VARCHAR(128),
    dataset_work_dir VARCHAR(512),
    params_json JSON,
    metrics_json JSON,
    run_fingerprint VARCHAR(64),
    source_fingerprint VARCHAR(64),
    requested_by VARCHAR(255),
    requested_from VARCHAR(64),
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE npc_training_run_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_run_id BIGINT,
    seq_no INTEGER,
    level VARCHAR(16),
    event_type VARCHAR(64),
    step VARCHAR(32),
    message TEXT,
    payload_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE npc_training_run_log_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_run_id BIGINT,
    stream_name VARCHAR(16),
    chunk_index INTEGER,
    chunk_text TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE npc_training_run_artifact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_run_id BIGINT,
    artifact_kind VARCHAR(32),
    file_path VARCHAR(512),
    file_size_bytes BIGINT,
    sha256 VARCHAR(64),
    metadata_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_npc_world_instances_instance_id
    ON npc_world_instances(instance_id);

CREATE INDEX idx_npc_episode_episode_uid
    ON npc_episode(episode_uid);

CREATE INDEX idx_npc_episode_turn_episode_turn
    ON npc_episode_turn(episode_id, turn_index);

CREATE INDEX idx_npc_episode_turn_fallback
    ON npc_episode_turn(deterministic_fallback_used);

CREATE INDEX idx_npc_sft_candidate_row_key
    ON npc_sft_candidate(row_key);

CREATE INDEX idx_npc_sft_candidate_canonical_row_key
    ON npc_sft_candidate(canonical_row_key);

CREATE INDEX idx_npc_sft_candidate_strategy
    ON npc_sft_candidate(strategy_label);

CREATE INDEX idx_npc_preference_pair_pair_key
    ON npc_preference_pair(pair_key);

CREATE INDEX idx_npc_review_task_status_kind
    ON npc_review_task(status, review_kind, priority);

CREATE INDEX idx_npc_dataset_snapshot_kind_active
    ON npc_dataset_snapshot(dataset_kind, is_active, generated_at);

CREATE INDEX idx_npc_training_run_state_kind
    ON npc_training_run(state, run_kind, created_at);

CREATE INDEX idx_npc_training_run_run_uid
    ON npc_training_run(run_uid);
