CREATE TABLE IF NOT EXISTS npc_visitor_owner (
    visitor_id VARCHAR(128) PRIMARY KEY,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS npc_visitor_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    is_owner BOOLEAN NOT NULL,
    world_instance_id VARCHAR(128),
    metadata_json JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_npc_visitor_event_created_at
    ON npc_visitor_event(created_at);

CREATE INDEX idx_npc_visitor_event_owner_type_created_at
    ON npc_visitor_event(is_owner, event_type, created_at);

CREATE INDEX idx_npc_visitor_event_visitor_created_at
    ON npc_visitor_event(visitor_id, created_at);
