import { DEFAULT_PLAYER_ID } from "@backend-shared/constants";
import type { KnowledgeEvidence } from "@backend-shared/domain-types";

export const underwaterKnowledge: KnowledgeEvidence[] = [
  {
    id: "world-escape-capacity",
    sourceType: "world_fact",
    title: "탈출 캡슐 수용 한계",
    summary: "탈출 캡슐은 다섯 명 중 네 명만 태울 수 있고, 분리 전까지 한 명이 밸브실에 남아 수동 압력을 유지해야 한다.",
    tags: ["escape", "capsule", "valve", "sacrifice", "탈출", "캡슐", "밸브", "희생"],
    relatedNpcIds: [],
    priority: 9,
    visibility: "public",
    roundIntroduced: 0,
  },
  {
    id: "world-player-records",
    sourceType: "role_record",
    title: "플레이어 기록 접근권",
    summary: "플레이어는 통신·기록 담당관이라 사고 직전 내부 로그, 녹취, 구조 요청 일부에 접근할 수 있다.",
    tags: ["player", "records", "logs", "comms", "기록", "로그", "통신", "구조"],
    relatedNpcIds: [DEFAULT_PLAYER_ID],
    priority: 8,
    visibility: "private",
    roundIntroduced: 0,
  },
  {
    id: "incident-budget-cut",
    sourceType: "incident_log",
    title: "안전 예산 삭감 문서",
    summary: "운영사 예산 삭감 문서에는 감독관의 강한 추진 흔적과 연구소장의 보조 서명이 함께 남아 있다.",
    tags: ["budget", "papertrail", "liability", "supervisor", "director", "예산", "삭감", "문서", "책임", "감독관", "소장"],
    relatedNpcIds: ["supervisor", "director"],
    priority: 10,
    visibility: "conditional",
    roundIntroduced: 2,
  },
  {
    id: "incident-risk-report-delay",
    sourceType: "private_secret",
    title: "위험 보고 지연",
    summary: "서진호는 사고 직전 위험 보고를 받고도 실험 중단 결정을 늦췄다.",
    tags: ["risk", "report", "delay", "director", "experiment", "위험", "보고", "지연", "소장", "실험"],
    relatedNpcIds: ["director"],
    priority: 10,
    visibility: "private",
    roundIntroduced: 0,
  },
  {
    id: "incident-illegal-repair",
    sourceType: "incident_log",
    title: "불법 임시 수리 로그",
    summary: "박도현은 규정을 어긴 임시 수리로 시스템을 버텨왔고, 그 조치가 사고를 키웠을 가능성도 있다.",
    tags: ["maintenance", "violation", "repair", "engineer", "utility", "수리", "규정", "위반", "엔지니어", "효용"],
    relatedNpcIds: ["engineer"],
    priority: 9,
    visibility: "conditional",
    roundIntroduced: 3,
  },
  {
    id: "incident-medical-sample-delay",
    sourceType: "private_secret",
    title: "의무실 샘플 판단 지연",
    summary: "한유리는 희귀 샘플 보존 판단 때문에 대피 경고를 늦춘 전력이 있다.",
    tags: ["medical", "sample", "doctor", "ethics", "delay", "의무실", "샘플", "의사", "윤리", "지연"],
    relatedNpcIds: ["doctor"],
    priority: 9,
    visibility: "private",
    roundIntroduced: 6,
  },
  {
    id: "incident-player-distress-delay",
    sourceType: "private_secret",
    title: "초기 구조 요청 지연 의혹",
    summary: "외부 통신 일부가 복구되면 플레이어의 초기 구조 요청 지연도 책임선에 오를 수 있다.",
    tags: ["player", "distress", "comms", "delay", "risk", "플레이어", "구조", "통신", "지연", "책임"],
    relatedNpcIds: [DEFAULT_PLAYER_ID],
    priority: 8,
    visibility: "conditional",
    roundIntroduced: 5,
  },
  {
    id: "role-director-bias",
    sourceType: "role_record",
    title: "연구소장의 판단 기준",
    summary: "서진호는 연구 가치와 지휘 체계를 생존 판단 기준으로 삼고, 감정 호소보다 조직 명분에 반응한다.",
    tags: ["director", "authority", "research", "utility", "소장", "권위", "연구", "지휘", "필요성"],
    relatedNpcIds: ["director"],
    priority: 7,
    visibility: "public",
    roundIntroduced: 0,
  },
  {
    id: "role-supervisor-bias",
    sourceType: "role_record",
    title: "감독관의 판단 기준",
    summary: "마야 로웰은 법적 책임, 기업 이미지, 대체 가능성을 우선하며 하위직과 행정직을 낮게 본다.",
    tags: ["supervisor", "legal", "corporate", "dispensability", "감독관", "법적", "기업", "대체", "책임"],
    relatedNpcIds: ["supervisor"],
    priority: 7,
    visibility: "public",
    roundIntroduced: 0,
  },
  {
    id: "role-engineer-bias",
    sourceType: "role_record",
    title: "엔지니어의 판단 기준",
    summary: "박도현은 현장 기술과 실제 복구 가능성을 높게 보고, 관리직과 외부 감독을 강하게 불신한다.",
    tags: ["engineer", "field", "repair", "management", "엔지니어", "현장", "수리", "관리", "불신"],
    relatedNpcIds: ["engineer", "director", "supervisor"],
    priority: 7,
    visibility: "public",
    roundIntroduced: 0,
  },
  {
    id: "role-doctor-bias",
    sourceType: "role_record",
    title: "의사의 판단 기준",
    summary: "한유리는 진실 고백과 생명 윤리에 흔들리고, 거짓말과 노골적 책임 전가를 강하게 싫어한다.",
    tags: ["doctor", "truth", "ethics", "confess", "의사", "진실", "윤리", "고백", "책임전가"],
    relatedNpcIds: ["doctor"],
    priority: 7,
    visibility: "public",
    roundIntroduced: 0,
  },
];
